//! Context fragment rendering for structured prompt sections.
//!
//! Each section (environment, skills, user instructions) is rendered as
//! an XML-tagged block, enabling the model to parse structured context
//! and supporting turn-to-turn incremental updates.

use super::types::{
    EnvironmentContext, UserInstructions, ENVIRONMENT_CONTEXT_CLOSE_TAG,
    ENVIRONMENT_CONTEXT_OPEN_TAG, SKILLS_INSTRUCTIONS_CLOSE_TAG, SKILLS_INSTRUCTIONS_OPEN_TAG,
    USER_INSTRUCTIONS_CLOSE_TAG, USER_INSTRUCTIONS_OPEN_TAG,
};

/// Render the environment context as an XML-tagged section.
///
/// Output format (aligned with Codex's `ContextualUserFragment`):
/// ```xml
/// <environment_context>
///   <cwd>/path/to/dir</cwd>
///   <os>macos (aarch64)</os>
///   <shell>zsh</shell>
///   <current_date>2026-01-15</current_date>
/// </environment_context>
/// ```
pub fn render_environment_context(ctx: &EnvironmentContext) -> String {
    let mut lines = Vec::new();
    lines.push(ENVIRONMENT_CONTEXT_OPEN_TAG.to_string());

    if let Some(ref cwd) = ctx.cwd {
        lines.push(format!("  <cwd>{}</cwd>", cwd.display()));
    }
    lines.push(format!("  <os>{} ({})</os>", ctx.os, ctx.arch));
    lines.push(format!("  <shell>{}</shell>", ctx.shell));

    if let Some(ref date) = ctx.current_date {
        lines.push(format!("  <current_date>{date}</current_date>"));
    }
    if let Some(ref tz) = ctx.timezone {
        lines.push(format!("  <timezone>{tz}</timezone>"));
    }

    lines.push(ENVIRONMENT_CONTEXT_CLOSE_TAG.to_string());
    lines.join("\n")
}

/// Render skills instructions as an XML-tagged developer section.
///
/// The `body` is generated by the budget-aware skill renderer in `skills/render.rs`.
pub fn render_skills_section(body: &str) -> String {
    if body.is_empty() {
        return String::new();
    }
    format!("{SKILLS_INSTRUCTIONS_OPEN_TAG}\n{body}\n{SKILLS_INSTRUCTIONS_CLOSE_TAG}")
}

/// Render user instructions as an XML-tagged section.
///
/// Includes the source directory for context (matching Codex's `UserInstructions`
/// which carries a `directory` field).
pub fn render_user_instructions(instructions: &UserInstructions) -> String {
    if instructions.is_empty() {
        return String::new();
    }
    let mut lines = Vec::new();
    lines.push(USER_INSTRUCTIONS_OPEN_TAG.to_string());
    if let Some(ref dir) = instructions.directory {
        lines.push(format!("  <directory>{dir}</directory>"));
    }
    lines.push(format!("  <content>\n{}\n  </content>", instructions.text));
    lines.push(USER_INSTRUCTIONS_CLOSE_TAG.to_string());
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_render_environment_context_full() {
        let ctx = EnvironmentContext {
            cwd: Some(PathBuf::from("/home/user/project")),
            shell: "zsh".to_string(),
            os: "macos".to_string(),
            arch: "aarch64".to_string(),
            current_date: Some("2026-05-05".to_string()),
            timezone: Some("+08:00".to_string()),
        };
        let rendered = render_environment_context(&ctx);
        assert!(rendered.contains("<environment_context>"));
        assert!(rendered.contains("</environment_context>"));
        assert!(rendered.contains("<cwd>/home/user/project</cwd>"));
        assert!(rendered.contains("<os>macos (aarch64)</os>"));
        assert!(rendered.contains("<shell>zsh</shell>"));
        assert!(rendered.contains("<current_date>2026-05-05</current_date>"));
        assert!(rendered.contains("<timezone>+08:00</timezone>"));
    }

    #[test]
    fn test_render_environment_context_minimal() {
        let ctx = EnvironmentContext {
            cwd: None,
            shell: "bash".to_string(),
            os: "linux".to_string(),
            arch: "x86_64".to_string(),
            current_date: None,
            timezone: None,
        };
        let rendered = render_environment_context(&ctx);
        assert!(rendered.contains("<os>linux (x86_64)</os>"));
        assert!(rendered.contains("<shell>bash</shell>"));
        assert!(!rendered.contains("<cwd>"));
        assert!(!rendered.contains("<current_date>"));
        assert!(!rendered.contains("<timezone>"));
    }

    #[test]
    fn test_render_skills_section_empty() {
        assert!(render_skills_section("").is_empty());
    }

    #[test]
    fn test_render_skills_section_with_content() {
        let body = "## Skills\n- alpha: desc (file: /path)";
        let rendered = render_skills_section(body);
        assert!(rendered.starts_with("<skills_instructions>"));
        assert!(rendered.ends_with("</skills_instructions>"));
        assert!(rendered.contains("## Skills"));
    }

    #[test]
    fn test_render_user_instructions_empty() {
        let empty = UserInstructions::new("");
        assert!(render_user_instructions(&empty).is_empty());
    }

    #[test]
    fn test_render_user_instructions_with_directory() {
        let instructions =
            UserInstructions::new("Follow code style").with_directory("/home/project");
        let rendered = render_user_instructions(&instructions);
        assert!(rendered.contains("<user_instructions>"));
        assert!(rendered.contains("</user_instructions>"));
        assert!(rendered.contains("<directory>/home/project</directory>"));
        assert!(rendered.contains("Follow code style"));
    }
}
