import { type CSSProperties } from "react";
import { theme } from "antd";

type ThemeToken = ReturnType<typeof theme.useToken>["token"];

export function createAgentChatStyles(
  isCompact: boolean,
  token: ThemeToken,
): Record<string, CSSProperties> {
  return {
    shell: {
      height: "100%",
      minHeight: 0,
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
    },
    body: {
      flex: 1,
      minHeight: 0,
      display: "grid",
      gridTemplateColumns: isCompact
        ? "minmax(0, 1fr) minmax(180px, 240px)"
        : "minmax(0, 1fr) 280px",
      gap: 16,
      overflow: "hidden",
    },
    conversationCard: {
      height: "100%",
      minHeight: 0,
      display: "flex",
      flexDirection: "column",
    },
    titleContent: {
      minWidth: 0,
      maxWidth: "100%",
      display: "flex",
      flexDirection: "column",
      gap: 4,
      padding: "2px 0",
    },
    titleMainLine: {
      minWidth: 0,
      display: "flex",
      alignItems: "center",
      gap: 8,
    },
    titleText: {
      minWidth: 0,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    titleActions: {
      flexShrink: 0,
    },
    conversation: {
      flex: 1,
      minHeight: 0,
      overflowY: "auto",
      padding: "28px 0 0",
      boxSizing: "border-box",
      scrollPaddingTop: 28,
      scrollbarGutter: "stable",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    conversationTrack: {
      width: "100%",
      maxWidth: 750,
      flex: "1 0 auto",
    },
    emptyMessages: {
      minHeight: 260,
      display: "grid",
      placeItems: "center",
      color: token.colorTextSecondary,
    },
    sideRail: {
      height: "100%",
      minHeight: 0,
      overflow: "hidden",
      display: "flex",
      flexDirection: "column",
    },
    threadCard: {
      height: "100%",
      minHeight: 0,
      display: "flex",
      flexDirection: "column",
    },
    threadCardBody: {
      flex: 1,
      minHeight: 0,
      height: "100%",
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
    },
    threadList: {
      width: "100%",
      maxWidth: "100%",
      flex: 1,
      minHeight: 0,
      height: "100%",
      display: "flex",
      flexDirection: "column",
      overflowY: "auto",
      overflowX: "hidden",
      padding: "4px 0",
    },
    threadVirtualSpace: {
      position: "relative",
      width: "100%",
      flex: "0 0 auto",
    },
    threadVirtualRow: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      paddingBottom: 2,
      boxSizing: "border-box",
    },
    threadLoadMoreBar: {
      flex: "0 0 auto",
      display: "flex",
      flexDirection: "column",
      gap: 6,
      padding: "8px 0 4px",
    },
    threadItem: {
      width: "100%",
      display: "flex",
      alignItems: "center",
      gap: 10,
      minWidth: 0,
      padding: "10px 12px",
      border: 0,
      borderRadius: 8,
      background: "transparent",
      color: token.colorText,
      cursor: "pointer",
      textAlign: "left",
    },
    threadItemSelected: {
      background: token.colorPrimaryBg,
      color: token.colorPrimary,
    },
    threadContextMenu: {
      minWidth: 170,
      borderRadius: 8,
      padding: 6,
      background: token.colorBgElevated,
      boxShadow: token.boxShadowSecondary,
      border: `1px solid ${token.colorBorderSecondary}`,
    },
    threadContextButton: {
      width: "100%",
      minHeight: 30,
      border: 0,
      borderRadius: 6,
      padding: "4px 10px",
      background: "transparent",
      color: token.colorText,
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      cursor: "pointer",
    },
    threadContextDangerButton: {
      color: token.colorError,
    },
    threadRunnerMark: {
      width: 30,
      height: 22,
      borderRadius: 7,
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      fontSize: 11,
      fontWeight: 600,
      background: token.colorFillSecondary,
      color: token.colorTextSecondary,
    },
    composer: {
      position: "sticky",
      bottom: 0,
      zIndex: 3,
      marginTop: "auto",
      padding: "12px 16px 8px",
      background: `linear-gradient(to top, ${token.colorBgContainer} 0%, ${token.colorBgContainer} 88%, transparent 100%)`,
      width: "100%",
      boxSizing: "border-box",
    },
    composerTrack: {
      width: "100%",
      maxWidth: 750,
      margin: "0 auto",
      padding: 12,
      boxSizing: "border-box",
      borderRadius: 14,
      border: `1px solid ${token.colorBorderSecondary}`,
      background: token.colorBgElevated,
      boxShadow: token.boxShadowSecondary,
    },
    inputWrap: {
      position: "relative",
      borderRadius: 10,
      background: token.colorBgElevated,
    },
    selectedRunnerPill: {
      position: "absolute",
      left: 12,
      top: 8,
      zIndex: 1,
      maxWidth: "calc(100% - 72px)",
      minHeight: 26,
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      padding: "2px 4px 2px 8px",
      borderRadius: 8,
      border: `1px solid ${token.colorBorderSecondary}`,
      background: token.colorFillSecondary,
      color: token.colorText,
      fontSize: 12,
      lineHeight: "18px",
      overflow: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    },
    selectedRunnerClear: {
      width: 20,
      height: 20,
      minWidth: 20,
      padding: 0,
      color: token.colorTextSecondary,
    },
    inputHint: {
      position: "absolute",
      left: 14,
      right: 58,
      bottom: 8,
      fontSize: 12,
      color: token.colorTextTertiary,
      overflow: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
      pointerEvents: "none",
    },
    queuePanel: {
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 8,
      padding: "8px 10px",
      background: token.colorFillQuaternary,
    },
    slashRunnerPanel: {
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 8,
      padding: "8px 10px",
      background: token.colorFillQuaternary,
      display: "flex",
      flexDirection: "column",
      gap: 6,
    },
    slashRunnerList: {
      display: "flex",
      flexDirection: "column",
      gap: 4,
      maxHeight: 160,
      overflowY: "auto",
    },
    slashRunnerOption: {
      width: "100%",
      minHeight: 32,
      border: 0,
      borderRadius: 6,
      background: "transparent",
      color: token.colorText,
      display: "flex",
      alignItems: "center",
      gap: 8,
      padding: "6px 8px",
      cursor: "pointer",
      textAlign: "left",
    },
    slashRunnerOptionText: {
      minWidth: 0,
      flex: 1,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    runnerCallChip: {
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      maxWidth: "100%",
      minHeight: 26,
      marginBottom: 8,
      padding: "2px 8px",
      borderRadius: 8,
      border: `1px solid ${token.colorBorderSecondary}`,
      background: token.colorFillQuaternary,
      color: token.colorTextSecondary,
      fontSize: 12,
      lineHeight: "18px",
      overflow: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    },
    runningInputToolbar: {
      display: "flex",
      justifyContent: "space-between",
      gap: 8,
      alignItems: "center",
    },
    sendInInput: {
      position: "absolute",
      right: 10,
      bottom: 8,
    },
    telemetrySection: {
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 10,
      padding: "8px 10px",
      background: token.colorFillQuaternary,
    },
    planPanel: {
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 6,
      background: token.colorFillQuaternary,
      overflow: "hidden",
    },
    planHeader: {
      width: "100%",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "5px 8px",
      minHeight: 30,
      boxSizing: "border-box",
    },
    planHeaderLabel: {
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      minWidth: 0,
      fontSize: 13,
      lineHeight: "18px",
    },
    planCountTag: {
      marginInlineEnd: 0,
      padding: "0 6px",
      fontSize: 11,
      lineHeight: "18px",
      height: 20,
    },
    planBody: {
      padding: "0 8px 8px",
    },
    planList: {
      maxHeight: 132,
      overflowY: "auto",
      overflowX: "hidden",
      scrollbarGutter: "stable",
      display: "flex",
      flexDirection: "column",
      gap: 3,
      paddingRight: 2,
    },
    planItem: {
      minHeight: 24,
      display: "flex",
      alignItems: "center",
      gap: 7,
      minWidth: 0,
      padding: "2px 6px",
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 6,
      background: token.colorFillQuaternary,
      boxSizing: "border-box",
    },
    planStatusIcon: {
      width: 14,
      height: 14,
      flexShrink: 0,
      fontSize: 14,
      lineHeight: "14px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
    },
    planPendingIcon: {
      width: 14,
      height: 14,
      flexShrink: 0,
      borderRadius: "50%",
      border: `1px solid ${token.colorTextQuaternary}`,
      background: "transparent",
      boxSizing: "border-box",
    },
    planStepText: {
      minWidth: 0,
      flex: 1,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      fontSize: 12,
      lineHeight: "18px",
    },
    runningDot: {
      width: 8,
      height: 8,
      borderRadius: "50%",
      background: token.colorSuccess,
      boxShadow: `0 0 0 3px ${token.colorSuccessBg}`,
      animation: "agent-chat-running-dot 1s ease-in-out infinite",
      flexShrink: 0,
    },
    settingsModalContent: {
      maxHeight: "70vh",
      overflowY: "auto",
      paddingRight: 4,
    },
  };
}
