import { type CSSProperties } from "react";
import { theme } from "antd";

type ThemeToken = ReturnType<typeof theme.useToken>["token"];

export function createAgentChatStyles(
  isCompact: boolean,
  isNarrow: boolean,
  threadRailCollapsed: boolean,
  token: ThemeToken,
  embeddedSidebar = false,
): Record<string, CSSProperties> {
  const horizontalPadding = embeddedSidebar || isNarrow ? 12 : isCompact ? 16 : 24;
  const conversationTopPadding = embeddedSidebar ? 12 : 28;
  const trackMaxWidth = embeddedSidebar ? 1120 : 750;
  return {
    shell: {
      height: "100%",
      minWidth: 0,
      minHeight: 0,
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
      padding: embeddedSidebar ? "24px 0 0" : undefined,
      boxSizing: embeddedSidebar ? "border-box" : undefined,
    },
    body: {
      position: "relative",
      flex: 1,
      minHeight: 0,
      display: "grid",
      minWidth: 0,
      gridTemplateColumns: embeddedSidebar || isNarrow || threadRailCollapsed
        ? "minmax(0, 1fr)"
        : isCompact
        ? "minmax(0, 1fr) minmax(180px, 240px)"
        : "minmax(0, 1fr) 280px",
      gap: 16,
      overflow: "hidden",
    },
    conversationCard: {
      height: "100%",
      minWidth: 0,
      minHeight: 0,
      display: "flex",
      flexDirection: "column",
    },
    threadRailExpandButton: {
      position: "absolute",
      top: 18,
      right: 12,
      zIndex: 8,
      width: 34,
      height: 34,
      minWidth: 34,
      padding: 0,
      borderRadius: "50%",
      color: token.colorText,
      background: token.colorBgElevated,
      border: `1px solid ${token.colorBorderSecondary}`,
      boxShadow: token.boxShadowSecondary,
      display: isNarrow ? "none" : "inline-flex",
      alignItems: "center",
      justifyContent: "center",
    },
    threadCardTitle: {
      width: "100%",
      minWidth: 0,
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    threadCardTitleMain: {
      minWidth: 0,
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      overflow: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    },
    threadCollapseButton: {
      flexShrink: 0,
      width: 28,
      height: 28,
      minWidth: 28,
      padding: 0,
    },
    titleContent: {
      minWidth: 0,
      maxWidth: "100%",
      display: "flex",
      flexDirection: "column",
      gap: 4,
      padding: "2px 0",
    },
    titleMainLine: {
      minWidth: 0,
      display: "flex",
      alignItems: "center",
      gap: 8,
    },
    titleText: {
      minWidth: 0,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    titleActions: {
      flexShrink: 0,
    },
    conversation: {
      flex: 1,
      minWidth: 0,
      minHeight: 0,
      overflowY: "auto",
      overflowX: "hidden",
      padding: `${conversationTopPadding}px ${horizontalPadding}px 0`,
      boxSizing: "border-box",
      scrollPaddingTop: conversationTopPadding,
      scrollbarGutter: "stable",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    conversationTrack: {
      width: "100%",
      minWidth: 0,
      maxWidth: trackMaxWidth,
      flex: "1 0 auto",
      paddingBottom: 72,
      boxSizing: "border-box",
    },
    emptyMessages: {
      minHeight: 260,
      display: "grid",
      placeItems: "center",
      color: token.colorTextSecondary,
    },
    sideRail: {
      height: "100%",
      minWidth: 0,
      minHeight: 0,
      overflow: "hidden",
      display: isNarrow ? "none" : "flex",
      flexDirection: "column",
    },
    threadCard: {
      height: "100%",
      minHeight: 0,
      display: "flex",
      flexDirection: "column",
    },
    threadCardBody: {
      flex: 1,
      minHeight: 0,
      height: "100%",
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
    },
    threadList: {
      width: "100%",
      maxWidth: "100%",
      flex: 1,
      minHeight: 0,
      height: "100%",
      display: "flex",
      flexDirection: "column",
      overflowY: "auto",
      overflowX: "hidden",
      padding: "4px 0",
    },
    threadVirtualSpace: {
      position: "relative",
      width: "100%",
      flex: "0 0 auto",
    },
    threadVirtualRow: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      paddingBottom: 2,
      boxSizing: "border-box",
    },
    threadLoadMoreBar: {
      flex: "0 0 auto",
      display: "flex",
      flexDirection: "column",
      gap: 6,
      padding: "8px 0 4px",
    },
    threadItem: {
      width: "100%",
      display: "flex",
      alignItems: "center",
      gap: 10,
      minWidth: 0,
      padding: "10px 12px",
      border: 0,
      borderRadius: 8,
      background: "transparent",
      color: token.colorText,
      cursor: "pointer",
      textAlign: "left",
    },
    threadItemSelected: {
      background: token.colorPrimaryBg,
      color: token.colorPrimary,
    },
    threadContextMenu: {
      minWidth: 170,
      borderRadius: 8,
      padding: 6,
      background: token.colorBgElevated,
      boxShadow: token.boxShadowSecondary,
      border: `1px solid ${token.colorBorderSecondary}`,
    },
    threadContextButton: {
      width: "100%",
      minHeight: 30,
      border: 0,
      borderRadius: 6,
      padding: "4px 10px",
      background: "transparent",
      color: token.colorText,
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      cursor: "pointer",
    },
    threadContextDangerButton: {
      color: token.colorError,
    },
    threadRunnerMark: {
      width: 30,
      height: 22,
      borderRadius: 7,
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      fontSize: 11,
      fontWeight: 600,
      background: token.colorFillSecondary,
      color: token.colorTextSecondary,
    },
    composer: {
      position: "sticky",
      bottom: 0,
      zIndex: 3,
      marginTop: "auto",
      padding: embeddedSidebar ? "12px 12px 8px" : isNarrow ? "12px 0 8px" : "12px 16px 8px",
      background: `linear-gradient(to top, ${token.colorBgContainer} 0%, ${token.colorBgContainer} 88%, transparent 100%)`,
      width: "100%",
      minWidth: 0,
      boxSizing: "border-box",
    },
    scrollToBottomLayer: {
      position: "absolute",
      left: 0,
      right: 0,
      top: -52,
      zIndex: 5,
      height: 44,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      transition: "opacity 180ms ease, transform 180ms ease",
      willChange: "opacity, transform",
    },
    scrollToBottomButton: {
      width: 42,
      height: 42,
      minWidth: 42,
      borderRadius: "50%",
      color: token.colorText,
      background: token.colorBgElevated,
      border: `1px solid ${token.colorBorderSecondary}`,
      boxShadow: token.boxShadowSecondary,
    },
    composerTrack: {
      position: "relative",
      width: "100%",
      minWidth: 0,
      maxWidth: trackMaxWidth,
      margin: "0 auto",
      padding: 12,
      boxSizing: "border-box",
      borderRadius: 14,
      border: `1px solid ${token.colorBorderSecondary}`,
      background: token.colorBgElevated,
      boxShadow: token.boxShadowSecondary,
    },
    inputWrap: {
      position: "relative",
      borderRadius: 10,
      background: token.colorBgElevated,
    },
    imagePreviewStrip: {
      display: "flex",
      flexWrap: "wrap",
      gap: 8,
      padding: "0 2px 8px",
    },
    imagePreviewItem: {
      position: "relative",
      width: 72,
      height: 72,
      borderRadius: 10,
      border: `1px solid ${token.colorBorderSecondary}`,
      overflow: "hidden",
      background: token.colorFillQuaternary,
    },
    imagePreviewThumb: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      display: "block",
    },
    imagePreviewRemove: {
      position: "absolute",
      top: 4,
      right: 4,
      width: 22,
      height: 22,
      minWidth: 22,
      padding: 0,
      borderRadius: "50%",
      background: token.colorBgElevated,
      color: token.colorText,
      boxShadow: token.boxShadowTertiary,
    },
    imagePreviewMeta: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      padding: "2px 5px",
      fontSize: 10,
      color: token.colorTextLightSolid,
      background: "rgba(0,0,0,0.55)",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    messageImageGrid: {
      display: "flex",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 6,
    },
    messageImageThumb: {
      width: 120,
      height: 90,
      objectFit: "cover",
      borderRadius: 10,
      border: `1px solid ${token.colorBorderSecondary}`,
      background: token.colorFillQuaternary,
    },
    tokenHud: {
      position: "absolute",
      left: 16,
      right: 16,
      top: -24,
      zIndex: 2,
      height: 14,
      display: "flex",
      alignItems: "center",
      gap: 8,
      color: token.colorTextQuaternary,
      pointerEvents: "none",
    },
    tokenHudItem: {
      flex: "0 1 auto",
      maxWidth: "min(300px, 46%)",
      overflow: "hidden",
      textOverflow: "ellipsis",
      fontSize: 11,
      lineHeight: "14px",
      whiteSpace: "nowrap",
    },
    tokenHudLabel: {
      color: token.colorTextQuaternary,
      fontSize: 11,
      lineHeight: "14px",
    },
    tokenHudValue: {
      color: token.colorTextTertiary,
      fontSize: 11,
      lineHeight: "14px",
      fontVariantNumeric: "tabular-nums",
    },
    tokenHudTrack: {
      display: "block",
      flex: "1 1 auto",
      minWidth: 48,
      height: 2,
      borderRadius: 999,
      background: token.colorFillQuaternary,
      overflow: "hidden",
    },
    tokenHudFill: {
      display: "block",
      height: "100%",
      borderRadius: 999,
      background: token.colorTextQuaternary,
      transition: "width 180ms ease",
    },
    selectedRunnerPill: {
      position: "absolute",
      left: 12,
      top: 8,
      zIndex: 1,
      maxWidth: "calc(100% - 72px)",
      minHeight: 26,
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      padding: "2px 4px 2px 8px",
      borderRadius: 8,
      border: `1px solid ${token.colorBorderSecondary}`,
      background: token.colorFillSecondary,
      color: token.colorText,
      fontSize: 12,
      lineHeight: "18px",
      overflow: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    },
    selectedRunnerClear: {
      width: 20,
      height: 20,
      minWidth: 20,
      padding: 0,
      color: token.colorTextSecondary,
    },
    planModePill: {
      position: "absolute",
      left: 12,
      top: 8,
      zIndex: 1,
      maxWidth: "calc(100% - 72px)",
      minHeight: 26,
      display: "inline-flex",
      alignItems: "center",
      padding: "2px 8px",
      borderRadius: 8,
      lineHeight: "20px",
      overflow: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    },
    inputHint: {
      position: "absolute",
      left: 14,
      right: 58,
      bottom: 8,
      fontSize: 12,
      color: token.colorTextTertiary,
      overflow: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
      pointerEvents: "none",
    },
    queuePanel: {
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 8,
      padding: "8px 10px",
      background: token.colorFillQuaternary,
    },
    queueList: {
      display: "flex",
      flexDirection: "column",
      gap: 6,
      maxHeight: 68,
      overflowY: "auto",
      paddingRight: 2,
      scrollbarGutter: "stable",
    },
    queueItem: {
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr) auto",
      alignItems: "center",
      gap: 8,
      minHeight: 31,
    },
    queueItemText: {
      minWidth: 0,
      overflow: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    },
    queueItemActions: {
      display: "inline-flex",
      alignItems: "center",
      gap: 4,
      flexShrink: 0,
      whiteSpace: "nowrap",
    },
    slashRunnerPanel: {
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 8,
      padding: "8px 10px",
      background: token.colorFillQuaternary,
      display: "flex",
      flexDirection: "column",
      gap: 6,
    },
    slashRunnerList: {
      display: "flex",
      flexDirection: "column",
      gap: 4,
      maxHeight: 160,
      overflowY: "auto",
    },
    slashRunnerOption: {
      width: "100%",
      minHeight: 32,
      border: 0,
      borderRadius: 6,
      background: "transparent",
      color: token.colorText,
      display: "flex",
      alignItems: "center",
      gap: 8,
      padding: "6px 8px",
      cursor: "pointer",
      textAlign: "left",
    },
    slashRunnerOptionActive: {
      background: token.colorFillSecondary,
    },
    slashRunnerOptionText: {
      minWidth: 0,
      flex: 1,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    runnerCallChip: {
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      maxWidth: "100%",
      minHeight: 26,
      marginBottom: 8,
      padding: "2px 8px",
      borderRadius: 8,
      border: `1px solid ${token.colorBorderSecondary}`,
      background: token.colorFillQuaternary,
      color: token.colorTextSecondary,
      fontSize: 12,
      lineHeight: "18px",
      overflow: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    },
    runningInputToolbar: {
      display: "flex",
      justifyContent: "space-between",
      gap: 8,
      alignItems: "center",
    },
    sendInInput: {
      position: "absolute",
      right: 10,
      bottom: 8,
    },
    telemetrySection: {
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 10,
      padding: "8px 10px",
      background: token.colorFillQuaternary,
    },
    planPanel: {
      position: "absolute",
      left: isNarrow ? 10 : 16,
      right: isNarrow ? 10 : 16,
      top: isNarrow ? -60 : -64,
      zIndex: 4,
      display: "flex",
      justifyContent: "center",
      pointerEvents: "auto",
    },
    planCapsule: {
      width: isNarrow ? "min(100%, 360px)" : "min(100%, 420px)",
      minHeight: 30,
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "4px 10px",
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 999,
      background: token.colorBgElevated,
      color: token.colorText,
      boxShadow: token.boxShadowTertiary,
      cursor: "default",
      boxSizing: "border-box",
    },
    planHeaderLabel: {
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      minWidth: 0,
      width: "100%",
      fontSize: 13,
      lineHeight: "18px",
      flex: "1 1 auto",
    },
    planProgressLabel: {
      flexShrink: 0,
      fontSize: 12,
      lineHeight: "18px",
      fontVariantNumeric: "tabular-nums",
    },
    planProgressTrack: {
      width: 42,
      height: 3,
      flexShrink: 0,
      borderRadius: 999,
      background: token.colorFillQuaternary,
      overflow: "hidden",
    },
    planProgressFill: {
      display: "block",
      height: "100%",
      borderRadius: 999,
      background: token.colorPrimary,
      transition: "width 180ms ease",
    },
    planCountTag: {
      marginInlineEnd: 0,
      padding: "0 6px",
      fontSize: 11,
      lineHeight: "18px",
      height: 20,
      flexShrink: 0,
    },
    planCurrentStep: {
      minWidth: 0,
      flex: "1 1 auto",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      color: token.colorTextSecondary,
      fontSize: 12,
      lineHeight: "18px",
    },
    planPopover: {
      position: "absolute",
      left: "50%",
      bottom: "calc(100% + 8px)",
      zIndex: 12,
      width: "min(480px, calc(100vw - 32px))",
      maxWidth: "calc(100vw - 32px)",
      transform: "translateX(-50%)",
      padding: 12,
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 12,
      background: token.colorBgElevated,
      boxShadow: token.boxShadowSecondary,
      boxSizing: "border-box",
    },
    planHoverBridge: {
      position: "absolute",
      left: "50%",
      bottom: "100%",
      zIndex: 11,
      width: "min(480px, calc(100vw - 32px))",
      height: 8,
      transform: "translateX(-50%)",
      background: "transparent",
      pointerEvents: "auto",
    },
    planPopoverHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 8,
    },
    planList: {
      maxHeight: 132,
      overflowY: "auto",
      overflowX: "hidden",
      scrollbarGutter: "stable",
      display: "flex",
      flexDirection: "column",
      gap: 3,
      paddingRight: 2,
    },
    planItem: {
      minHeight: 24,
      display: "flex",
      alignItems: "center",
      gap: 7,
      minWidth: 0,
      padding: "2px 6px",
      border: `1px solid ${token.colorBorderSecondary}`,
      borderRadius: 6,
      background: token.colorFillQuaternary,
      boxSizing: "border-box",
    },
    planStatusIcon: {
      width: 14,
      height: 14,
      flexShrink: 0,
      fontSize: 14,
      lineHeight: "14px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
    },
    planPendingIcon: {
      width: 14,
      height: 14,
      flexShrink: 0,
      borderRadius: "50%",
      border: `1px solid ${token.colorTextQuaternary}`,
      background: "transparent",
      boxSizing: "border-box",
    },
    planStepText: {
      minWidth: 0,
      flex: 1,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      fontSize: 12,
      lineHeight: "18px",
    },
    planStatusText: {
      flexShrink: 0,
      fontSize: 11,
      lineHeight: "18px",
      color: token.colorTextTertiary,
    },
    runningDot: {
      width: 8,
      height: 8,
      borderRadius: "50%",
      background: token.colorSuccess,
      boxShadow: `0 0 0 3px ${token.colorSuccessBg}`,
      animation: "agent-chat-running-dot 1s ease-in-out infinite",
      flexShrink: 0,
    },
    settingsModalContent: {
      maxHeight: "70vh",
      overflowY: "auto",
      paddingRight: 4,
    },
  };
}
