pub mod admin_api;
pub mod body_cache;
pub mod body_manipulation;
pub mod brute_force;
pub mod client_process;
pub mod curl_mock;
pub mod dns;
pub mod filters;
pub mod group_rules;
pub mod https;
pub mod im_gateway_agent;
pub mod install_skill;
pub mod matchers;
pub mod mock_traffic;
pub mod protocols;
pub mod public;
pub mod remote_file_api;
pub mod remote_shell_exec;
pub mod replay_sse;
pub mod request;
pub mod request_modification;
pub mod response;
pub mod response_modification;
pub mod routing;
pub mod rule_merge_strategy;
pub mod rule_priority;
pub mod rule_validation;
pub mod status_redirect;
pub mod template;
pub mod tls_config_disconnect;
pub mod tls_intercept_mode;
pub mod tls_switch_test;
pub mod traffic_cli;
pub mod url_manipulation;
pub mod userpass_auth;
pub mod ws_payload_persistence;

use crate::runner::TestCase;

pub fn all_tests() -> Vec<TestCase> {
    let mut tests = Vec::new();
    tests.extend(routing::get_all_tests());
    tests.extend(admin_api::get_all_tests());
    tests.extend(brute_force::get_all_tests());
    tests.extend(replay_sse::get_all_tests());
    tests.extend(request::tests());
    tests.extend(response::tests());
    tests.extend(template::tests());
    tests.extend(public::tests());
    tests.extend(remote_file_api::get_all_tests());
    tests.extend(remote_shell_exec::get_all_tests());
    tests.extend(curl_mock::get_all_tests());
    tests.extend(https::get_all_tests());
    tests.extend(protocols::get_all_tests());
    tests.extend(matchers::get_all_tests());
    tests.extend(request_modification::get_all_tests());
    tests.extend(response_modification::get_all_tests());
    tests.extend(rule_merge_strategy::get_all_tests());
    tests.extend(rule_priority::get_all_tests());
    tests.extend(rule_validation::get_all_tests());
    tests.extend(body_manipulation::get_all_tests());
    tests.extend(url_manipulation::get_all_tests());
    tests.extend(status_redirect::get_all_tests());
    tests.extend(filters::get_all_tests());
    tests.extend(dns::get_all_tests());
    tests.extend(tls_intercept_mode::get_all_tests());
    tests.extend(tls_config_disconnect::get_all_tests());
    tests.extend(tls_switch_test::get_all_tests());
    tests.extend(body_cache::get_all_tests());
    tests.extend(client_process::get_all_tests());
    tests.extend(traffic_cli::get_all_tests());
    tests.extend(ws_payload_persistence::get_all_tests());
    tests.extend(userpass_auth::get_all_tests());
    tests.extend(install_skill::get_all_tests());
    tests.extend(group_rules::get_all_tests());
    tests.extend(mock_traffic::get_all_tests());
    tests.extend(im_gateway_agent::get_all_tests());
    tests
}
